# Generated by Django 3.1.2 on 2021-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210717_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationoutput',
            name='run_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
